### ISSUE TITLE
Api changed. 

### ISSUE THREAD

**Issue by thornick** [bertreb/pimatic-landroid#1]
Hi.
Am still using Pimatic and this Plugin.
2 weeks ago the api has been changed, which prevents to let the plugin to log in. 
Iobroker (js based) is also having a plugin for worx mower and the developer made changes to have it working again. I havent made much progress to be honest to get this working again. Would you have the time to look into this?
https://github.com/Lucky-ESA/ioBroker.worx/blob/460925d782ccd3737a83e241699a4a9357caaa44/main.js

**Comment by bertreb** [comment]
Hi, i stopped some time ago working on pimatic plugins and switched to Home-assistant. 
I own a Landroid mower and use the Landroid integration in Home-assistant. That integration suffered also from the api change, but it was fixed within a few days. So, i like the way Home-assistant works and how it is enhanced/maintained.
Pimatic is unmaintained (the core and most of the plugins). It can still be ok, but at some point in time a plugin will stop working (as you noticed).
I can't help you any further, and suggest to migrate to a maintained solution.

**Comment by thornick** [comment]
Understand. Seems that there is no other way from a long-term perspective to move to another solution. Thanks anyway.
Am also looking into Homeassistant.
